# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{project}
  s.version = "0.1.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David J. Hamilton"]
  s.date = %q{2010-08-27}
  s.default_executable = %q{project}
  s.description = %q{create projects, either on gitosis or github.}
  s.email = %q{project@hjdivad.com}
  s.executables = ["project"]
  s.extra_rdoc_files = [
    "README.txt"
  ]
  s.files = [
    ".ditz-config",
     ".ditz-plugins",
     ".ditz/issue-2925a332105c58f6bcefe9d75a990ed8630e672a.yaml",
     ".ditz/issue-4e0632aa8e64ac7782ad0256e71ec49c77253314.yaml",
     ".ditz/issue-7f9f0ffcd84b6990145594debcc8f3d3bb1b049d.yaml",
     ".ditz/issue-9cae4187c3227b70d47bc62ae13863295795163d.yaml",
     ".ditz/issue-a0cb440fcf1bd28859d43f424763792be533bf21.yaml",
     ".ditz/issue-a8644551775019b303de237f4ea8a00944242e8e.yaml",
     ".ditz/issue-f9e030473afcf31a5734317217f5edcea3990ffe.yaml",
     ".ditz/project.yaml",
     ".gitignore",
     ".gvimrc",
     ".rvmrc",
     ".vimproject",
     "Gemfile",
     "Gemfile.lock",
     "History.rdoc",
     "Manifest.txt",
     "README.txt",
     "Rakefile",
     "VERSION.yml",
     "bin/project",
     "lib/project.rb",
     "lib/project/basic.rb",
     "lib/project/git.rb",
     "lib/project/github.rb",
     "lib/project/gitosis.rb",
     "lib/project/tasks.rb",
     "lib/project/tasks/versioning.rake",
     "lib/project/util.rb",
     "project.gemspec",
     "share/project-completion",
     "share/templates/lake/.gvimrc",
     "share/templates/lake/.vimproject",
     "share/templates/lake/Rakefile",
     "share/templates/ruby/.gvimrc",
     "share/templates/ruby/.rspec",
     "share/templates/ruby/.rvmrc",
     "share/templates/ruby/.vim/ftplugin/.gitignore",
     "share/templates/ruby/.vim/plugin/.gitignore",
     "share/templates/ruby/.vimproject",
     "share/templates/ruby/Gemfile",
     "share/templates/ruby/History.rdoc",
     "share/templates/ruby/LICENSE",
     "share/templates/ruby/README.rdoc",
     "share/templates/ruby/Rakefile",
     "share/templates/ruby/VERSION.yml",
     "share/templates/ruby/autotest/discover.rb",
     "share/templates/ruby/features/project.feature",
     "share/templates/ruby/features/support/env.rb",
     "share/templates/ruby/spec/spec_helper.rb"
  ]
  s.homepage = %q{http://example.com}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{create projects}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<trollop>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 1.4.0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["= 1.3.0"])
      s.add_development_dependency(%q<project>, ["~> 0.1"])
    else
      s.add_dependency(%q<trollop>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 1.4.0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rspec>, ["= 1.3.0"])
      s.add_dependency(%q<project>, ["~> 0.1"])
    end
  else
    s.add_dependency(%q<trollop>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 1.4.0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rspec>, ["= 1.3.0"])
    s.add_dependency(%q<project>, ["~> 0.1"])
  end
end

