#!/usr/bin/env ruby

require 'rubygems'
require 'hoe'
require 'spec'
require 'spec/rake/spectask'


Hoe.spec 'project_name' do
	developer( 'David JH', 'davidjh@hjdivad.com' )

	self.version = "0.0.1"
	# self.rubyforge_name = 'project_name'
end


# Spec ################################################################ {{{

$append_spec_opts = ''

namespace :spec do

	Spec::Rake::SpecTask.new( :run_spec ) do |t|
		t.spec_opts = proc do
			[ "--color --format specdoc #{$append_spec_opts}" ]
		end
	end

	task :spec, [ :spec_to_run ] do |t, args|
		$append_spec_opts = "-e #{args.spec_to_run}" unless args.spec_to_run.nil?
		Rake.application.invoke_task( "spec:run_spec" )
	end

end

desc "Run specs.  If +spec_to_run+ is specified, run only that spec."
task :spec, [ :spec_to_run ] => "spec:spec"

# }}}






# vim: syntax=ruby

